import OverflowMenu from './client/OverflowMenu';
import './globals.css'
import ClassicFooter from './server/ClassicFooter';

async function getData() {
  const res = await fetch('http://localhost:3000/api/profile');
  return res.json();
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const { firstName } = await getData();
  const pageTitle = `${firstName}'s Portfolio`;

  return (
    <html lang="en">
      <head>
        <title>{pageTitle}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body>
        <OverflowMenu />
        {children}
        <ClassicFooter />
      </body>
    </html>
  )
}
